apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vllm
  janus-idp.io/tekton: vllm
  backstage.io/kubernetes-id: vllm
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vllm
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml