---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: vllm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vllm 
  name: vllm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi